### ISSUE TITLE
Add settings schema and implement readme build process

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/safety-delta-delta#12]
Use safety-histogram [scripts](https://github.com/RhoInc/safety-histogram/tree/master/scripts) as a template

**Comment by jwildfire** [comment]
![deltadelta_animated](https://user-images.githubusercontent.com/3680095/67397935-51e39880-f580-11e9-8ff0-a6ae930745eb.gif)

**Comment by samussiah** [comment]
Addressed in [v1.0.0](https://github.com/RhoInc/safety-delta-delta/releases/tag/v1.0.0).
