### ISSUE TITLE
Fix precision of data points between chart points and detail table

### ISSUE THREAD

**Issue by dschwentker** [RhoInc/safety-delta-delta#21]
When you click on a data point in the chart, the details table shows the change over time values to two decimal precision. When you hover over a data point in the chart, it shows the values to three decimal precision. This can lead to values that don't quite seem to match, i.e., 0.005 when hovering shows as 0.00 in the details table. Seems like the precision should be the same in both places so that the values match.

**Comment by jwildfire** [comment]
Updated hover precision to 2 decimal places to match the table.
